### ISSUE TITLE
bea8711 之后用 python 3.11 跑出错

### ISSUE THREAD

**Issue by hrzhu** [xfgryujk/blivechat#120]
bea8711 之后用 python 3.11 跑出错， 3.10 及以前的版本没问题。

```
2023-08-28 09:37:47,389 ERROR [services.translate]: TencentTranslateFree error:
Traceback (most recent call last):
  File "/home/h/playground/blivechat/services/translate.py", line 255, in _translate_consumer
    task = await _pop_task()
           ^^^^^^^^^^^^^^^^^
  File "/home/h/playground/blivechat/services/translate.py", line 186, in _pop_task
    done_future_set, pending_future_set = await asyncio.wait(
                                          ^^^^^^^^^^^^^^^^^^^
  File "/home/h/.pyenv/versions/3.11.5/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```
https://docs.python.org/3/library/asyncio-task.html#asyncio.wait

**Comment by xfgryujk** [comment]
11
