### ISSUE TITLE
无法正常启动

### ISSUE THREAD

**Issue by huoyan1231** [xfgryujk/blivechat#148]
2023-11-29 16:23:40,654 INFO [__main__]: App started, initializing
2023-11-29 16:23:40,793 WARNING [__main__]: Address is used 127.0.0.1:12450
2023-11-29 16:23:41,155 ERROR [asyncio]: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000018B9DFB86D0>
--- Logging error ---
--- Logging error ---
Exception ignored in: <function ClientSession.__del__ at 0x0000018B9C785430>
Traceback (most recent call last):
  File "aiohttp\client.py", line 348, in __del__
  File "asyncio\base_events.py", line 1740, in call_exception_handler
  File "logging\__init__.py", line 1475, in error
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 954, in handle
  File "logging\__init__.py", line 1093, in emit
  File "logging\__init__.py", line 1007, in handleError
  File "traceback.py", line 103, in print_exception
  File "traceback.py", line 508, in __init__
  File "traceback.py", line 366, in extract
  File "traceback.py", line 288, in line
  File "linecache.py", line 16, in getline
  File "linecache.py", line 47, in getlines
  File "linecache.py", line 103, in updatecache
  File "PyInstaller\loader\pyimod03_importers.py", line 342, in get_source
NameError: name 'open' is not defined

**Comment by Xeler-ync** [comment]
```
2023-11-29 16:23:40,793 WARNING [main]: Address is used 127.0.0.1:12450
```
端口12450可能被占用，可以检查一下是否被其他进程占用或者换一个端口

**Comment by huoyan1231** [comment]
> ```
> 2023-11-29 16:23:40,793 WARNING [main]: Address is used 127.0.0.1:12450
> ```
> 
> 端口12450可能被占用，可以检查一下是否被其他进程占用或者换一个端口

换了好几个端口都是一样的报错
netstat也查不到相关端口占用

**Comment by huoyan1231** [comment]
> 你重启电脑再试吧

好好，重启电脑解决95%问题
