### ISSUE TITLE
弹幕姬开启一段时间后就无法再显示新弹幕，并且报错

### ISSUE THREAD

**Issue by cym1932** [xfgryujk/blivechat#188]
报错信息：（看起来似乎是网络问题，然而直播是正常进行的证明网络没有问题，并且每次启动后确实能用几分钟）
2024-04-04 21:06:15,154 INFO [__main__]: App started, initializing
2024-04-04 21:06:15,327 INFO [__main__]: Server started: 127.0.0.1:12450
2024-04-04 21:06:15,327 INFO [__main__]: Running event loop
2024-04-04 21:06:15,334 INFO [services.translate]: TencentTranslateFree waiting to become available
2024-04-04 21:06:15,731 INFO [services.translate]: TencentTranslateFree became available
2024-04-04 21:06:18,700 INFO [api.open_live]: client=127.0.0.1 requesting open live, cls=StartGamePublicHandler
2024-04-04 21:06:22,706 INFO [api.open_live]: client=127.0.0.1 requesting open live, cls=StartGamePublicHandler
2024-04-04 21:06:29,167 ERROR [api.open_live]: Request common server failed:
Traceback (most recent call last):
  File "api\open_live.py", line 124, in _read_response
  File "aiohttp\client.py", line 1194, in __aenter__
  File "aiohttp\client.py", line 682, in _request
  File "aiohttp\helpers.py", line 735, in __exit__
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\open_live.py", line 63, in request_open_live_or_common_server
  File "api\open_live.py", line 132, in _read_response
api.open_live.TransportError: TimeoutError:
2024-04-04 21:06:29,168 ERROR [tornado.access]: 500 POST /api/open_live/start_game (127.0.0.1) 10468.23ms
2024-04-04 21:06:33,178 ERROR [api.open_live]: Request common server failed:
Traceback (most recent call last):
  File "api\open_live.py", line 124, in _read_response
  File "aiohttp\client.py", line 1194, in __aenter__
  File "aiohttp\client.py", line 682, in _request
  File "aiohttp\helpers.py", line 735, in __exit__
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\open_live.py", line 63, in request_open_live_or_common_server
  File "api\open_live.py", line 132, in _read_response
api.open_live.TransportError: TimeoutError:
2024-04-04 21:06:33,179 ERROR [tornado.access]: 500 POST /api/open_live/start_game (127.0.0.1) 10473.08ms
2024-04-04 21:06:34,475 INFO [api.open_live]: client=127.0.0.1 requesting open live, cls=StartGamePublicHandler
2024-04-04 21:06:35,605 INFO [api.open_live]: client=127.0.0.1 room_id=13630599 start game res: 0 0, game_id=6f63f16d-083b-4956-a405-a4222c5c69f0
2024-04-04 21:08:06,176 ERROR [api.open_live]: Request common server failed:
Traceback (most recent call last):
  File "api\open_live.py", line 124, in _read_response
  File "aiohttp\client.py", line 1194, in __aenter__
  File "aiohttp\client.py", line 682, in _request
  File "aiohttp\helpers.py", line 735, in __exit__
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\open_live.py", line 63, in request_open_live_or_common_server
  File "api\open_live.py", line 132, in _read_response
api.open_live.TransportError: TimeoutError:
2024-04-04 21:08:06,177 ERROR [api.open_live]: client=127.0.0.1 game heartbeat failed, game_id=6f63f16d-083b-4956-a405-a4222c5c69f0, error: TimeoutError:
2024-04-04 21:08:06,178 ERROR [tornado.access]: 500 POST /api/open_live/game_heartbeat (127.0.0.1) 10959.94ms
2024-04-04 21:09:02,173 ERROR [api.open_live]: Request common server failed:
Traceback (most recent call last):
  File "api\open_live.py", line 124, in _read_response
  File "aiohttp\client.py", line 1194, in __aenter__
  File "aiohttp\client.py", line 682, in _request
  File "aiohttp\helpers.py", line 735, in __exit__
asyncio.exceptions.TimeoutError

**Comment by xfgryujk** [comment]
https://github.com/xfgryujk/blivechat/discussions/187
