### ISSUE TITLE
腾讯翻译白嫖版好像不能用了

### ISSUE THREAD

**Issue by sileence114** [xfgryujk/blivechat#49]
```
2021-08-21 19:16:33 INFO [__main__]: Server started: 127.0.0.1:12450
2021-08-21 19:16:33 ERROR [models.translate]: TencentTranslateFree init failed: initial global variables not found
NoneType: None
```

**Comment by xfgryujk** [comment]
不修了，用官方接口吧

**Comment by sileence114** [comment]
可能是服务器波动 重启一下又好了……

**Comment by sileence114** [comment]
又试了下 确实会经常崩。。。  
不打算修的话就不管他了
```
2021-08-21 19:31:25 INFO [__main__]: Server started: 127.0.0.1:12450
2021-08-21 19:31:25 INFO [api.chat]: Websocket connected 127.0.0.1
2021-08-21 19:31:25 INFO [api.chat]: Client 127.0.0.1 is joining room 3044248
2021-08-21 19:31:25 INFO [api.chat]: Creating room 3044248
2021-08-21 19:31:26 INFO [api.chat]: 1 rooms
2021-08-21 19:31:26 INFO [api.chat]: 1 clients in room 3044248
2021-08-21 19:31:29 WARNING [blivedm.blivedm]: room 3044248 未知命令：cmd=STOP_LIVE_ROOM_LIST {'cmd': 'STOP_LIVE_ROOM_LIST', 'data': {'room_id_list': [13614986, 21115791, 13333535, 23469392, 4179750, 8273582, 21024256, 12273, 23304521, 3881337, 22016681, 23469036, 22904277, 23398091, 3288495, 572749, 15150857, 22280145, 6763093, 12766036, 15080846, 21194928, 23137058, 3549474, 4363147, 7961434, 11804581, 21596258, 2179705, 23311852, 23469281, 22399176, 9467171, 21953566, 5983485, 23151598, 2326556, 2761492, 11782682, 23165017, 23460144, 5796610, 8814930, 23336960, 23371475, 2769589, 3786361, 4578834, 13807107, 22646365, 23176514, 23324717, 397093, 957010, 23144478, 9445274, 23466026, 276851, 2849423, 3094995, 4581805, 13103618, 21287878, 22778488, 2880225, 8782676, 993184, 22873631, 5571565, 21715386, 1555354, 7273351, 22204649, 23447902, 313010, 12707294, 23449919, 23469028, 6842427, 23235187, 23467664, 2720628, 10264382]}}
2021-08-21 19:31:30 INFO [api.chat]: Websocket disconnected 127.0.0.1 room: 3044248
2021-08-21 19:31:30 INFO [api.chat]: 0 clients in room 3044248
2021-08-21 19:31:30 INFO [api.chat]: Removing room 3044248
2021-08-21 19:31:30 INFO [api.chat]: 0 rooms
2021-08-21 19:31:31 INFO [api.chat]: Websocket connected 127.0.0.1
2021-08-21 19:31:31 INFO [api.chat]: Client 127.0.0.1 is joining room 3044248
2021-08-21 19:31:31 INFO [api.chat]: Creating room 3044248
2021-08-21 19:31:31 INFO [api.chat]: 1 rooms
2021-08-21 19:31:31 INFO [api.chat]: 1 clients in room 3044248
2021-08-21 19:31:50 WARNING [blivedm.blivedm]: room 3044248 未知命令：cmd=ONLINE_RANK_COUNT {'cmd': 'ONLINE_RANK_COUNT', 'data': {'count': 17}}
2021-08-21 19:32:25 ERROR [models.translate]: TencentTranslateFree init failed: initial global variables not found
NoneType: None
2021-08-21 19:33:26 ERROR [models.translate]: TencentTranslateFree init failed: initial global variables not found
NoneType: None
2021-08-21 19:34:26 WARNING [models.translate]: TencentTranslateFree init request failed: reauthuri=reauth12f, status=404 Not Found
2021-08-21 19:34:56 WARNING [models.translate]: TencentTranslateFree init request failed: reauthuri=reauth12f, status=404 Not Found
2021-08-21 19:34:58 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545698780', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545698780', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '任天堂，谢谢李', 'targetText': '', 'traceId': '1270fa4b2971414a96b6ea150b71f061'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:05 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545705819', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545705819', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '好刮', 'targetText': '', 'traceId': '10e7a8a67ceb4b0e8d061e5fca2c989f'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:09 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545709275', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545709275', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': 'zc的翘臀，嘤嘤嘤', 'targetText': '', 'traceId': 'c135177c7cac49ccbfc868900860b0ea'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:11 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545711138', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545711138', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '请不要去其他主播那里刷Zc，违者本直播间将同步禁言~', 'targetText': '', 'traceId': '46b60f409ba24c5c940092fec9592c63'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:12 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545712870', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545712870', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '刮痧', 'targetText': '', 'traceId': 'e3055e824f104e12b4710ccf02939ecc'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:15 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545715391', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545715391', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '一般来说宅家人一天两关差不多了', 'targetText': '', 'traceId': 'dd132ad520914ffa868ad87c810c947c'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:16 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545716329', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545716329', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '小翅膀同款好臀～', 'targetText': '', 'traceId': 'a92b22aa1006481bbecb9cfda984b836'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:35:23 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545723350', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545723350', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '你是该健健身了', 'targetText': '', 'traceId': '8b0c7377161c4f959e0e559ee6929790'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:36:56 WARNING [models.translate]: TencentTranslateFree init request failed: reauthuri=reauth12f, status=404 Not Found
2021-08-21 19:37:26 ERROR [models.translate]: TencentTranslateFree init failed: initial global variables not found
NoneType: None
2021-08-21 19:37:26 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545846651', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545846651', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '太猛了我的妈', 'targetText': '', 'traceId': '3d9991a1358441a08d518ad7f1c64433'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:37:44 ERROR [asyncio]: Task exception was never retrieved
future: <Task finished coro=<ClientWebSocketResponse.send_bytes() done, defined at C:\ProgramData\Miniconda3\envs\py36\lib\site-packages\aiohttp\client_ws.py:152> exception=ConnectionResetError('Cannot write to closing transport',)>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py36\lib\site-packages\aiohttp\client_ws.py", line 155, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "C:\ProgramData\Miniconda3\envs\py36\lib\site-packages\aiohttp\http_websocket.py", line 685, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "C:\ProgramData\Miniconda3\envs\py36\lib\site-packages\aiohttp\http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-08-21 19:37:48 WARNING [blivedm.blivedm]: room 3044248 掉线重连中1
2021-08-21 19:37:54 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545874337', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545874337', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '弹幕好多音游人', 'targetText': '', 'traceId': 'b23037f9b5e8416a912fa0e681d812dd'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:37:54 WARNING [models.translate]: TencentTranslateFree result is empty {'sessionUuid': 'default_uuid_1629545874838', 'translate': {'errCode': 0, 'errMsg': '', 'sessionUuid': 'default_uuid_1629545874838', 'source': 'zh', 'target': 'jp', 'records': [{'sourceText': '好耶', 'targetText': '', 'traceId': 'e289474f0040439fb9f048a0d400199d'}], 'full': True, 'options': {}}, 'dict': None, 'suggest': None, 'errCode': 0, 'errMsg': 'ok'}
2021-08-21 19:38:12 WARNING [blivedm.blivedm]: room 3044248 未知命令：cmd=ONLINE_RANK_V2 {'cmd': 'ONLINE_RANK_V2', 'data': {'list': [{'uid': 362898527, 'face': 'http://i2.hdslb.com/bfs/face/2baf02c937c00cca8a815c9842d0cc323b4d7ab9.jpg', 'score': '1680', 'uname': 'Jokey玖克', 'rank': 1, 'guard_level': 3}, {'uid': 3946919, 'face': 'http://i2.hdslb.com/bfs/face/36723ebeea8ea393d29357d9b4228f58eb53b329.jpg', 'score': '1382', 'uname': '花笑玥', 'rank': 2, 'guard_level': 3}, {'uid': 454114782, 'face': 'http://i0.hdslb.com/bfs/face/a290385a623c13598568b1cd2a4603fc2108f456.jpg', 'score': '1380', 'uname': '罗奕洛', 'rank': 3, 'guard_level': 3}, {'uid': 13320945, 'face': 'http://i0.hdslb.com/bfs/face/9543c51036db453e6269f133ddeb930c475c03df.jpg', 'score': '693', 'uname': 'zc爱吃糯米团子', 'rank': 4, 'guard_level': 2}, {'uid': 481258594, 'face': 'http://i1.hdslb.com/bfs/face/7dca10354311ba1ba494c721c8027cdf11f37e4d.jpg', 'score': '297', 'uname': '司徒书竹半邪', 'rank': 5, 'guard_level': 0}, {'uid': 5175447, 'face': 'http://i0.hdslb.com/bfs/face/8412625c44d3f322dec6a5e50da884300fc66d4b.jpg', 'score': '280', 'uname': '无响应送终人', 'rank': 6, 'guard_level': 3}, {'uid': 168838010, 'face': 'http://i2.hdslb.com/bfs/face/1391cb64f0fddafe6a07e8f5384236a7ebcc63b6.jpg', 'score': '110', 'uname': '天狗桑', 'rank': 7, 'guard_level': 0}], 'rank_type': 'gold-rank'}}
```
