### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by L1ulee** [xfgryujk/blivechat#67]
在运行npm run build时出错

``` 
> blivechat@1.6.0 build
> vue-cli-service build


⠹  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/liulee/Documents/blivechat/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/liulee/Documents/blivechat/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/Users/liulee/Documents/blivechat/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/cache-loader/dist/index.js:240:7
    at /Users/liulee/Documents/blivechat/frontend/node_modules/neo-async/async.js:2830:7
    at done (/Users/liulee/Documents/blivechat/frontend/node_modules/neo-async/async.js:2865:11)
    at /Users/liulee/Documents/blivechat/frontend/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/Users/liulee/Documents/blivechat/frontend/node_modules/cache-loader/dist/index.js:229:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.7.2
```

**Comment by xfgryujk** [comment]
加环境变量`NODE_OPTIONS=--openssl-legacy-provider`

**Comment by L1ulee** [comment]
谢谢，已解决！
