### ISSUE TITLE
自行部署在python main.py时出错

### ISSUE THREAD

**Issue by RAINighty** [xfgryujk/blivechat#70]
windows sever 2012
PS D:\blive\blivechat> python main.py
Traceback (most recent call last):
  File "D:\blive\blivechat\main.py", line 11, in <module>
    import api.chat
  File "D:\blive\blivechat\api\chat.py", line 15, in <module>
    import blivedm.blivedm.client as blivedm_client
ModuleNotFoundError: No module named 'blivedm.blivedm'

**Comment by xfgryujk** [comment]
参考README使用方法

**Comment by xfgryujk** [comment]
浏览器输入公网IP:端口
