### ISSUE TITLE
头像api失效

### ISSUE THREAD

**Issue by AnzhiZhang** [xfgryujk/blivechat#96]
```
2023-01-04 09:57:48 ERROR [tornado.access]: 500 GET /api/avatar_url?uid=***(127.0.0.1) 359.63ms
2023-01-04 09:59:14 ERROR [tornado.application]: Uncaught exception GET /api/avatar_url?uid=*** (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:12450', method='GET', uri='/api/avatar_url?uid=***', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "tornado\web.py", line 1704, in _execute
  File "api\chat.py", line 343, in get
  File "services\avatar.py", line 54, in get_avatar_url_or_none
  File "services\avatar.py", line 141, in _get_avatar_url_from_web_coroutine
  File "services\avatar.py", line 171, in _do_get_avatar_url_from_web
KeyError: 'face'
```

**Comment by xfgryujk** [comment]
Duplicate of #84
