### ISSUE TITLE
[Python 3.10] TypeError: gather() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by cdfmlr** [xfgryujk/blivechat#99]
Python 3.10 移除了 `asyncio.gather` 的 `loop` 参数，导致 blivedm 以及 blivechat 的服务器转发模式无法正常工作。

Python 文档相关说明：

- https://docs.python.org/release/3.10.0/library/asyncio-task.html#asyncio.gather

错误日志：

```
2023-02-13 17:04:05 ERROR [blivedm]: room=000000, body={'cmd': 'INTERACT_WORD', 'data': {'contribution': {'grade': 0}, 'core_user_type': 0, 'dmscore': 16, 'fans_medal': {'anchor_roomid': 000000, 'guard_level': 0, 'icon_id': 0, 'is_lighted': 1, 'medal_color': 12478086, 'medal_color_border': 12478086, 'medal_color_end': 12478086, 'medal_color_start': 12478086, 'medal_level': 15, 'medal_name': 'FTJ', 'score': 97200, 'special': '', 'target_id': 51628309}, 'identities': [3, 1], 'is_spread': 0, 'msg_type': 1, 'privilege_type': 0, 'roomid': 000000, 'score': 1676386246403, 'spread_desc': '', 'spread_info': '', 'tail_icon': 0, 'timestamp': 1676279046, 'trigger_time': 1676279045285873700, 'uid': 000000, 'uname': '魔鬼', 'uname_color': ''}}
2023-02-13 17:04:05 ERROR [blivedm]: room= 000000 _parse_ws_message() error:
Traceback (most recent call last):
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 494, in _on_ws_message
    await self._parse_ws_message(message.data)
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 518, in _parse_ws_message
    await self._parse_business_message(header, body)
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 559, in _parse_business_message
    await self._parse_ws_message(body)
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 518, in _parse_ws_message
    await self._parse_business_message(header, body)
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 565, in _parse_business_message
    await self._handle_command(body)
  File "/Users/c/Projects/muvtuber/blivechat/blivedm/blivedm/client.py", line 596, in _handle_command
    asyncio.gather(
TypeError: gather() got an unexpected keyword argument 'loop'
```

**Comment by xfgryujk** [comment]
已知，准备修复了
